name: Hello

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
            
        

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello, GitHub Actions!"
