name: SendMessage

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
#      - '.github/workflows/notifications.yml'

jobs:
  Check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.9
      - name: install python packages
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: check updates
        id: checkupdates
        run: |
          echo "::set-output name=AFTER::$(git diff ${{ github.event.before }} ${{ github.event.after }} | grep -E '+_Некоторые особенности .*' ) "
          echo "::set-output name=BEFORE::$(git diff ${{ github.event.before }} ${{ github.event.after }} | grep -E '-_Некоторые особенности .*' ) "
      - name: get updates
        id: getupdates
        run: ::set-output name=PROJECT_NAME::$(AFTER=${{ steps.checkupdates.outputs.AFTER }} BEFORE=${{ steps.checkupdates.outputs.BEFORE }} python3 get_updates.py)
      
      - name: send message
        run: TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} CHAT_ID=${{ secrets.CHAT_ID }} PROJECT_NAME=${{ steps.getupdates.outputs.PROJECT_NAME }} python3 send_message.py
