name: SendMessage

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/notifications.yml'

jobs:
  Check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: check updates
        id: checkupdates
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.base_ref}} ${{ github.event.before }}| xargs) "
      - name: get updates
        run: |
          echo "Hello"
      
      - name: send message
        run: TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} CHAT_ID=${{ secrets.CHAT_ID }} PROJECT_NAME="Hello" python3 send_message.py
