name: SendMessage

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  Check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: check updates
        id: checkupdates
        continue-on-error: false
        run: |
          echo "::set-output name=grepValue::$( git diff ${{ github.event.before }}..${{ github.sha }} )"
          # if [ echo "$( git diff --name-only ${{ github.event.before }}..${{ github.sha }})" ]
          # then
          #  echo "There are no updates on tips"
          #  exit 1
          # fi
      - name: get updates
        run: |
          echo "::set-output name=grepValue::$( git diff ${{ github.event.before }}..${{ github.sha }} | grep -c '^proxy' )"
      
      - name: send message
        run: |
          python send_message.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PROJECT_NAME: ""
