name: Hello

on: [push]
    repository:
        - name:
            Linux_features_42tests
    paths:
        - 'README.md'

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello, GitHub Actions!"
